"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Ship, Save, Plus, Edit, Trash2, Package, DollarSign, Users } from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { toast } from "@/hooks/use-toast"

export function ShipchandlerConfig() {
  const [autoCalculateSupplies, setAutoCalculateSupplies] = useState(true)
  const [requireCaptainApproval, setRequireCaptainApproval] = useState(true)
  const [enableInventoryTracking, setEnableInventoryTracking] = useState(true)
  const [autoGenerateDeliveryNote, setAutoGenerateDeliveryNote] = useState(true)
  const [showNewProductDialog, setShowNewProductDialog] = useState(false)
  const [showNewSupplierDialog, setShowNewSupplierDialog] = useState(false)
  const [showNewVesselDialog, setShowNewVesselDialog] = useState(false)
  const [editingItem, setEditingItem] = useState<any>(null)
  const [editDialogType, setEditDialogType] = useState<"product" | "supplier" | "vessel" | null>(null)

  const [products, setProducts] = useState([
    {
      id: "1",
      code: "FUEL001",
      name: "Combustible Marino",
      category: "Combustibles",
      unit: "Litros",
      price: 1.25,
      currency: "USD",
      stock: 50000,
    },
    {
      id: "2",
      code: "FOOD001",
      name: "Provisiones Frescas",
      category: "Alimentos",
      unit: "Kg",
      price: 8.5,
      currency: "USD",
      stock: 2500,
    },
    {
      id: "3",
      code: "WATER001",
      name: "Agua Potable",
      category: "Agua",
      unit: "Litros",
      price: 0.15,
      currency: "USD",
      stock: 100000,
    },
    {
      id: "4",
      code: "SPARE001",
      name: "Repuestos Motor",
      category: "Repuestos",
      unit: "Unidad",
      price: 450.0,
      currency: "USD",
      stock: 25,
    },
  ])

  const [suppliers, setSuppliers] = useState([
    {
      id: "1",
      name: "Marine Fuel Supply Co.",
      category: "Combustibles",
      contact: "Juan Pérez",
      phone: "+507 6123-4567",
      rating: 4.8,
    },
    {
      id: "2",
      name: "Fresh Food Distributors",
      category: "Alimentos",
      contact: "María López",
      phone: "+507 6234-5678",
      rating: 4.6,
    },
    {
      id: "3",
      name: "Technical Parts Ltd.",
      category: "Repuestos",
      contact: "Carlos Ruiz",
      phone: "+507 6345-6789",
      rating: 4.9,
    },
  ])

  const [vesselTypes, setVesselTypes] = useState([
    { id: "1", type: "Container Ship", description: "Buque Portacontenedores", baseRate: 500, active: true },
    { id: "2", type: "Bulk Carrier", description: "Granelero", baseRate: 400, active: true },
    { id: "3", type: "Tanker", description: "Petrolero", baseRate: 600, active: true },
    { id: "4", type: "Cruise Ship", description: "Crucero", baseRate: 800, active: false },
  ])

  // Form states
  const [newProduct, setNewProduct] = useState({
    code: "",
    name: "",
    category: "Combustibles",
    unit: "",
    price: "",
    currency: "USD",
    stock: "",
  })

  const [newSupplier, setNewSupplier] = useState({
    name: "",
    category: "Combustibles",
    contact: "",
    phone: "",
    rating: "4.5",
  })

  const [newVessel, setNewVessel] = useState({
    type: "",
    description: "",
    baseRate: "",
    active: true,
  })

  const handleSaveConfig = () => {
    toast({
      title: "Configuración guardada",
      description: "Los cambios han sido guardados exitosamente.",
    })
  }

  const handleAddProduct = () => {
    if (newProduct.code && newProduct.name && newProduct.unit && newProduct.price && newProduct.stock) {
      const id = (products.length + 1).toString()
      setProducts([
        ...products,
        {
          id,
          ...newProduct,
          price: Number(newProduct.price),
          stock: Number(newProduct.stock),
        },
      ])
      setNewProduct({
        code: "",
        name: "",
        category: "Combustibles",
        unit: "",
        price: "",
        currency: "USD",
        stock: "",
      })
      setShowNewProductDialog(false)
      toast({
        title: "Producto agregado",
        description: `Producto ${newProduct.name} agregado exitosamente.`,
      })
    }
  }

  const handleAddSupplier = () => {
    if (newSupplier.name && newSupplier.contact && newSupplier.phone) {
      const id = (suppliers.length + 1).toString()
      setSuppliers([
        ...suppliers,
        {
          id,
          ...newSupplier,
          rating: Number(newSupplier.rating),
        },
      ])
      setNewSupplier({
        name: "",
        category: "Combustibles",
        contact: "",
        phone: "",
        rating: "4.5",
      })
      setShowNewSupplierDialog(false)
      toast({
        title: "Proveedor agregado",
        description: `Proveedor ${newSupplier.name} agregado exitosamente.`,
      })
    }
  }

  const handleAddVessel = () => {
    if (newVessel.type && newVessel.description && newVessel.baseRate) {
      const id = (vesselTypes.length + 1).toString()
      setVesselTypes([
        ...vesselTypes,
        {
          id,
          ...newVessel,
          baseRate: Number(newVessel.baseRate),
        },
      ])
      setNewVessel({
        type: "",
        description: "",
        baseRate: "",
        active: true,
      })
      setShowNewVesselDialog(false)
      toast({
        title: "Tipo de buque agregado",
        description: `Tipo de buque ${newVessel.type} agregado exitosamente.`,
      })
    }
  }

  const handleEditItem = () => {
    if (editDialogType === "product" && editingItem) {
      setProducts(
        products.map((product) =>
          product.id === editingItem.id
            ? {
                ...editingItem,
                price: Number(editingItem.price),
                stock: Number(editingItem.stock),
              }
            : product,
        ),
      )
      toast({
        title: "Producto actualizado",
        description: `Producto ${editingItem.name} actualizado exitosamente.`,
      })
    } else if (editDialogType === "supplier" && editingItem) {
      setSuppliers(
        suppliers.map((supplier) =>
          supplier.id === editingItem.id
            ? {
                ...editingItem,
                rating: Number(editingItem.rating),
              }
            : supplier,
        ),
      )
      toast({
        title: "Proveedor actualizado",
        description: `Proveedor ${editingItem.name} actualizado exitosamente.`,
      })
    } else if (editDialogType === "vessel" && editingItem) {
      setVesselTypes(
        vesselTypes.map((vessel) =>
          vessel.id === editingItem.id
            ? {
                ...editingItem,
                baseRate: Number(editingItem.baseRate),
              }
            : vessel,
        ),
      )
      toast({
        title: "Tipo de buque actualizado",
        description: `Tipo de buque ${editingItem.type} actualizado exitosamente.`,
      })
    }
    setEditingItem(null)
    setEditDialogType(null)
  }

  const handleDeleteItem = (type: "product" | "supplier" | "vessel", id: string) => {
    if (type === "product") {
      setProducts(products.filter((product) => product.id !== id))
      toast({
        title: "Producto eliminado",
        description: "El producto ha sido eliminado exitosamente.",
      })
    } else if (type === "supplier") {
      setSuppliers(suppliers.filter((supplier) => supplier.id !== id))
      toast({
        title: "Proveedor eliminado",
        description: "El proveedor ha sido eliminado exitosamente.",
      })
    } else if (type === "vessel") {
      setVesselTypes(vesselTypes.filter((vessel) => vessel.id !== id))
      toast({
        title: "Tipo de buque eliminado",
        description: "El tipo de buque ha sido eliminado exitosamente.",
      })
    }
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-lg bg-green-500 flex items-center justify-center">
          <Ship className="h-6 w-6 text-white" />
        </div>
        <div>
          <h1 className="text-3xl font-bold">Configuración - Shipchandler</h1>
          <p className="text-muted-foreground">Configuración específica para servicios de abastecimiento a barcos</p>
        </div>
      </div>

      <Tabs defaultValue="general" className="w-full">
        <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 md:w-auto md:inline-grid">
          <TabsTrigger value="general">
            <Ship className="h-4 w-4 mr-2" />
            General
          </TabsTrigger>
          <TabsTrigger value="products">
            <Package className="h-4 w-4 mr-2" />
            Productos
          </TabsTrigger>
          <TabsTrigger value="suppliers">
            <Users className="h-4 w-4 mr-2" />
            Proveedores
          </TabsTrigger>
          <TabsTrigger value="vessels">
            <DollarSign className="h-4 w-4 mr-2" />
            Tipos de Buque
          </TabsTrigger>
        </TabsList>

        <TabsContent value="general" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Configuración General de Shipchandler</CardTitle>
              <CardDescription>Ajustes generales para servicios de abastecimiento a barcos</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="auto-calculate-supplies">Cálculo Automático de Suministros</Label>
                    <p className="text-sm text-muted-foreground">
                      Calcular automáticamente cantidades basadas en tipo de buque y duración del viaje
                    </p>
                  </div>
                  <Switch
                    id="auto-calculate-supplies"
                    checked={autoCalculateSupplies}
                    onCheckedChange={setAutoCalculateSupplies}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="captain-approval">Aprobación del Capitán Requerida</Label>
                    <p className="text-sm text-muted-foreground">
                      Requerir aprobación del capitán antes de entregar suministros
                    </p>
                  </div>
                  <Switch
                    id="captain-approval"
                    checked={requireCaptainApproval}
                    onCheckedChange={setRequireCaptainApproval}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="inventory-tracking">Seguimiento de Inventario</Label>
                    <p className="text-sm text-muted-foreground">
                      Activar seguimiento automático de inventario en tiempo real
                    </p>
                  </div>
                  <Switch
                    id="inventory-tracking"
                    checked={enableInventoryTracking}
                    onCheckedChange={setEnableInventoryTracking}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label htmlFor="auto-delivery-note">Nota de Entrega Automática</Label>
                    <p className="text-sm text-muted-foreground">
                      Generar notas de entrega automáticamente al completar suministro
                    </p>
                  </div>
                  <Switch
                    id="auto-delivery-note"
                    checked={autoGenerateDeliveryNote}
                    onCheckedChange={setAutoGenerateDeliveryNote}
                  />
                </div>
                <Separator />
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="default-currency">Moneda Predeterminada</Label>
                    <Select defaultValue="USD">
                      <SelectTrigger id="default-currency">
                        <SelectValue placeholder="Seleccionar moneda" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="USD">USD - Dólar Estadounidense</SelectItem>
                        <SelectItem value="EUR">EUR - Euro</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="invoice-prefix">Prefijo de Factura</Label>
                    <Input id="invoice-prefix" defaultValue="SC-" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="delivery-window">Ventana de Entrega (horas)</Label>
                    <Input id="delivery-window" type="number" defaultValue="4" />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="markup-percentage">Margen de Ganancia (%)</Label>
                    <Input id="markup-percentage" type="number" defaultValue="15" />
                  </div>
                </div>
              </div>
              <Button onClick={handleSaveConfig}>
                <Save className="mr-2 h-4 w-4" />
                Guardar Configuración
              </Button>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="products" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Catálogo de Productos</CardTitle>
              <CardDescription>Gestionar productos y servicios disponibles para suministro</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-end">
                <Button onClick={() => setShowNewProductDialog(true)}>
                  <Plus className="mr-2 h-4 w-4" />
                  Nuevo Producto
                </Button>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Código</TableHead>
                    <TableHead>Producto</TableHead>
                    <TableHead>Categoría</TableHead>
                    <TableHead>Unidad</TableHead>
                    <TableHead>Precio</TableHead>
                    <TableHead>Stock</TableHead>
                    <TableHead className="text-right">Acciones</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {products.map((product) => (
                    <TableRow key={product.id}>
                      <TableCell className="font-medium">{product.code}</TableCell>
                      <TableCell>{product.name}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{product.category}</Badge>
                      </TableCell>
                      <TableCell>{product.unit}</TableCell>
                      <TableCell>
                        ${product.price} {product.currency}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={product.stock > 1000 ? "success" : product.stock > 100 ? "default" : "destructive"}
                        >
                          {product.stock.toLocaleString()}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex gap-1 justify-end">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => {
                              setEditingItem(product)
                              setEditDialogType("product")
                            }}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => handleDeleteItem("product", product.id)}>
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="suppliers" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Gestión de Proveedores</CardTitle>
              <CardDescription>Administrar proveedores y sus datos de contacto</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-end">
                <Button onClick={() => setShowNewSupplierDialog(true)}>
                  <Plus className="mr-2 h-4 w-4" />
                  Nuevo Proveedor
                </Button>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Proveedor</TableHead>
                    <TableHead>Categoría</TableHead>
                    <TableHead>Contacto</TableHead>
                    <TableHead>Teléfono</TableHead>
                    <TableHead>Rating</TableHead>
                    <TableHead className="text-right">Acciones</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {suppliers.map((supplier) => (
                    <TableRow key={supplier.id}>
                      <TableCell className="font-medium">{supplier.name}</TableCell>
                      <TableCell>
                        <Badge variant="outline">{supplier.category}</Badge>
                      </TableCell>
                      <TableCell>{supplier.contact}</TableCell>
                      <TableCell>{supplier.phone}</TableCell>
                      <TableCell>⭐ {supplier.rating}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex gap-1 justify-end">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => {
                              setEditingItem(supplier)
                              setEditDialogType("supplier")
                            }}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => handleDeleteItem("supplier", supplier.id)}>
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="vessels" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Tipos de Buque y Tarifas</CardTitle>
              <CardDescription>Configurar tipos de buque y sus tarifas base</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-end">
                <Button onClick={() => setShowNewVesselDialog(true)}>
                  <Plus className="mr-2 h-4 w-4" />
                  Nuevo Tipo
                </Button>
              </div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Tipo</TableHead>
                    <TableHead>Descripción</TableHead>
                    <TableHead>Tarifa Base</TableHead>
                    <TableHead>Estado</TableHead>
                    <TableHead className="text-right">Acciones</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {vesselTypes.map((vessel) => (
                    <TableRow key={vessel.id}>
                      <TableCell className="font-medium">{vessel.type}</TableCell>
                      <TableCell>{vessel.description}</TableCell>
                      <TableCell>${vessel.baseRate} USD</TableCell>
                      <TableCell>
                        <Badge variant={vessel.active ? "success" : "secondary"}>
                          {vessel.active ? "Activo" : "Inactivo"}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-right">
                        <div className="flex gap-1 justify-end">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => {
                              setEditingItem(vessel)
                              setEditDialogType("vessel")
                            }}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button variant="ghost" size="sm" onClick={() => handleDeleteItem("vessel", vessel.id)}>
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Modales para agregar/editar productos */}
      <Dialog open={showNewProductDialog} onOpenChange={setShowNewProductDialog}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Agregar Nuevo Producto</DialogTitle>
            <DialogDescription>Complete los detalles para agregar un nuevo producto.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="code">Código</Label>
                <Input
                  id="code"
                  value={newProduct.code}
                  onChange={(e) => setNewProduct({ ...newProduct, code: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="category">Categoría</Label>
                <Select
                  value={newProduct.category}
                  onValueChange={(value) => setNewProduct({ ...newProduct, category: value })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Combustibles">Combustibles</SelectItem>
                    <SelectItem value="Alimentos">Alimentos</SelectItem>
                    <SelectItem value="Agua">Agua</SelectItem>
                    <SelectItem value="Repuestos">Repuestos</SelectItem>
                    <SelectItem value="Lubricantes">Lubricantes</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="name">Nombre del Producto</Label>
              <Input
                id="name"
                value={newProduct.name}
                onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })}
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="unit">Unidad</Label>
                <Input
                  id="unit"
                  value={newProduct.unit}
                  onChange={(e) => setNewProduct({ ...newProduct, unit: e.target.value })}
                  placeholder="ej. Litros, Kg, Unidad"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="currency">Moneda</Label>
                <Select
                  value={newProduct.currency}
                  onValueChange={(value) => setNewProduct({ ...newProduct, currency: value })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="USD">USD</SelectItem>
                    <SelectItem value="EUR">EUR</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="price">Precio</Label>
                <Input
                  id="price"
                  type="number"
                  step="0.01"
                  value={newProduct.price}
                  onChange={(e) => setNewProduct({ ...newProduct, price: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="stock">Stock Inicial</Label>
                <Input
                  id="stock"
                  type="number"
                  value={newProduct.stock}
                  onChange={(e) => setNewProduct({ ...newProduct, stock: e.target.value })}
                />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNewProductDialog(false)}>
              Cancelar
            </Button>
            <Button onClick={handleAddProduct}>Guardar</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal para nuevo proveedor */}
      <Dialog open={showNewSupplierDialog} onOpenChange={setShowNewSupplierDialog}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Agregar Nuevo Proveedor</DialogTitle>
            <DialogDescription>Complete los detalles para agregar un nuevo proveedor.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="supplier-name">Nombre del Proveedor</Label>
              <Input
                id="supplier-name"
                value={newSupplier.name}
                onChange={(e) => setNewSupplier({ ...newSupplier, name: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="supplier-category">Categoría</Label>
              <Select
                value={newSupplier.category}
                onValueChange={(value) => setNewSupplier({ ...newSupplier, category: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Combustibles">Combustibles</SelectItem>
                  <SelectItem value="Alimentos">Alimentos</SelectItem>
                  <SelectItem value="Agua">Agua</SelectItem>
                  <SelectItem value="Repuestos">Repuestos</SelectItem>
                  <SelectItem value="Lubricantes">Lubricantes</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="contact">Persona de Contacto</Label>
              <Input
                id="contact"
                value={newSupplier.contact}
                onChange={(e) => setNewSupplier({ ...newSupplier, contact: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="supplier-phone">Teléfono</Label>
              <Input
                id="supplier-phone"
                value={newSupplier.phone}
                onChange={(e) => setNewSupplier({ ...newSupplier, phone: e.target.value })}
                placeholder="ej. +507 6123-4567"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="supplier-rating">Rating</Label>
              <Input
                id="supplier-rating"
                type="number"
                step="0.1"
                min="1"
                max="5"
                value={newSupplier.rating}
                onChange={(e) => setNewSupplier({ ...newSupplier, rating: e.target.value })}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNewSupplierDialog(false)}>
              Cancelar
            </Button>
            <Button onClick={handleAddSupplier}>Guardar</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modal para nuevo tipo de buque */}
      <Dialog open={showNewVesselDialog} onOpenChange={setShowNewVesselDialog}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Agregar Nuevo Tipo de Buque</DialogTitle>
            <DialogDescription>Complete los detalles para agregar un nuevo tipo de buque.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="vessel-type">Tipo de Buque</Label>
              <Input
                id="vessel-type"
                value={newVessel.type}
                onChange={(e) => setNewVessel({ ...newVessel, type: e.target.value })}
                placeholder="ej. Container Ship"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="vessel-description">Descripción</Label>
              <Input
                id="vessel-description"
                value={newVessel.description}
                onChange={(e) => setNewVessel({ ...newVessel, description: e.target.value })}
                placeholder="ej. Buque Portacontenedores"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="vessel-baseRate">Tarifa Base (USD)</Label>
              <Input
                id="vessel-baseRate"
                type="number"
                value={newVessel.baseRate}
                onChange={(e) => setNewVessel({ ...newVessel, baseRate: e.target.value })}
              />
            </div>
            <div className="flex items-center space-x-2">
              <Switch
                id="vessel-active"
                checked={newVessel.active}
                onCheckedChange={(checked) => setNewVessel({ ...newVessel, active: checked })}
              />
              <Label htmlFor="vessel-active">Activo</Label>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNewVesselDialog(false)}>
              Cancelar
            </Button>
            <Button onClick={handleAddVessel}>Guardar</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Modales de edición similares a los de Trucking... */}
      {/* Por brevedad, incluiré solo uno como ejemplo */}
      <Dialog
        open={editDialogType === "product" && !!editingItem}
        onOpenChange={() => {
          if (editDialogType === "product") {
            setEditingItem(null)
            setEditDialogType(null)
          }
        }}
      >
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Editar Producto</DialogTitle>
            <DialogDescription>Modifique los detalles del producto.</DialogDescription>
          </DialogHeader>
          {editingItem && editDialogType === "product" && (
            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-code">Código</Label>
                  <Input
                    id="edit-code"
                    value={editingItem.code}
                    onChange={(e) => setEditingItem({ ...editingItem, code: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-category">Categoría</Label>
                  <Select
                    value={editingItem.category}
                    onValueChange={(value) => setEditingItem({ ...editingItem, category: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Combustibles">Combustibles</SelectItem>
                      <SelectItem value="Alimentos">Alimentos</SelectItem>
                      <SelectItem value="Agua">Agua</SelectItem>
                      <SelectItem value="Repuestos">Repuestos</SelectItem>
                      <SelectItem value="Lubricantes">Lubricantes</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-name">Nombre del Producto</Label>
                <Input
                  id="edit-name"
                  value={editingItem.name}
                  onChange={(e) => setEditingItem({ ...editingItem, name: e.target.value })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-unit">Unidad</Label>
                  <Input
                    id="edit-unit"
                    value={editingItem.unit}
                    onChange={(e) => setEditingItem({ ...editingItem, unit: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-currency">Moneda</Label>
                  <Select
                    value={editingItem.currency}
                    onValueChange={(value) => setEditingItem({ ...editingItem, currency: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="USD">USD</SelectItem>
                      <SelectItem value="EUR">EUR</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-price">Precio</Label>
                  <Input
                    id="edit-price"
                    type="number"
                    step="0.01"
                    value={editingItem.price}
                    onChange={(e) => setEditingItem({ ...editingItem, price: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-stock">Stock</Label>
                  <Input
                    id="edit-stock"
                    type="number"
                    value={editingItem.stock}
                    onChange={(e) => setEditingItem({ ...editingItem, stock: e.target.value })}
                  />
                </div>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setEditingItem(null)
                setEditDialogType(null)
              }}
            >
              Cancelar
            </Button>
            <Button onClick={handleEditItem}>Guardar Cambios</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
