// Opciones para los campos dinámicos del XML de Trucking

export const TRUCKING_OPTIONS = {
  // Business Type - se guarda I o E en el XML
  businessType: [
    { value: "IMPORT", label: "Import", xmlValue: "I" },
    { value: "EXPORT", label: "Export", xmlValue: "E" }
  ],

  // Container ISO Code - se guarda el código completo (ej: 42G0)
  containerIsoCode: [
    { code: "10G0", description: "10G0 - GENERAL PURPOSE CONT." },
    { code: "10T0", description: "10T0 - TANK CONTAINER" },
    { code: "12R1", description: "12R1 - REEFER CONTAINER" },
    { code: "20G0", description: "20G0 - GENERAL PURPOSE CONT." },
    { code: "20G1", description: "20G1 - GENERAL PURPOSE CONT." },
    { code: "20H0", description: "20H0 - INSULATED CONTAINER" },
    { code: "20P1", description: "20P1 - FLAT (FIXED ENDS)" },
    { code: "20T0", description: "20T0 - TANK CONTAINER" },
    { code: "20T1", description: "20T1 - TANK CONTAINER" },
    { code: "20T2", description: "20T2 - TANK CONTAINER" },
    { code: "20T3", description: "20T3 - TANK CONTAINER" },
    { code: "20T4", description: "20T4 - TANK CONTAINER" },
    { code: "20T5", description: "20T5 - TANK CONTAINER" },
    { code: "20T6", description: "20T6 - TANK CONTAINER" },
    { code: "20T7", description: "20T7 - TANK CONTAINER" },
    { code: "20T8", description: "20T8 - TANK CONTAINER" },
    { code: "22B0", description: "22B0 - BULK CONTAINER" },
    { code: "22G0", description: "22G0 - GENERAL PURPOSE CONT." },
    { code: "22G1", description: "22G1 - GENERAL PURPOSE CONT." },
    { code: "22H0", description: "22H0 - INSULATED CONTAINER" },
    { code: "22K2", description: "22K2 - Fodstuff tank Container" },
    { code: "22OS", description: "22OS - OPEN SIDE" },
    { code: "22P1", description: "22P1 - FLAT (FIXED ENDS)" },
    { code: "22P3", description: "22P3 - FLAT (COLLAPSIBLE)" },
    { code: "22P7", description: "22P7 - FLAT (GENSET CARRIER)" },
    { code: "22P8", description: "22P8 - FLAT (COLL.FLUSH FOLDING)" },
    { code: "22P9", description: "22P9 - FLAT (COLLAPSIBLE)" },
    { code: "22R1", description: "22R1 - REEFER CONTAINER" },
    { code: "22R7", description: "22R7 - BUILT-IN GEN. F. POWER SPLY OF REEF" },
    { code: "22R9", description: "22R9 - REEFER CONT.(NO FOOD)" },
    { code: "22S1", description: "22S1 - NAMED CARGO CONTAINER" },
    { code: "22T0", description: "22T0 - TANK CONTAINER" },
    { code: "22T1", description: "22T1 - TANK CONTAINER" },
    { code: "22T2", description: "22T2 - TANK CONTAINER" },
    { code: "22T3", description: "22T3 - TANK CONTAINER" },
    { code: "22T4", description: "22T4 - TANK CONTAINER" },
    { code: "22T5", description: "22T5 - TANK CONTAINER" },
    { code: "22T6", description: "22T6 - TANK CONTAINER" },
    { code: "22T7", description: "22T7 - TANK CONTAINER" },
    { code: "22T8", description: "22T8 - TANK CONTAINER" },
    { code: "22U1", description: "22U1 - OPEN TOP CONTAINER" },
    { code: "22U6", description: "22U6 - HARDTOP CONTAINER" },
    { code: "22V0", description: "22V0 - VENTILATED CONTAINER" },
    { code: "22V2", description: "22V2 - VENTILATED CONTAINER" },
    { code: "22V3", description: "22V3 - VENTILATED CONTAINER" },
    { code: "22W0", description: "22W0 - PALLETWIDE" },
    { code: "24T6", description: "24T6 - TANK CONTAINER" },
    { code: "24W1", description: "24W1 - TANK PALLETWIDE" },
    { code: "24ZZ", description: "24ZZ - Unspecified" },
    { code: "25G0", description: "25G0 - GP-CONTAINER OVER-HEIGHT" },
    { code: "25P0", description: "25P0 - HIGH CUBE PLATFORM" },
    { code: "26G0", description: "26G0 - GP-CONTAINER OVER-HEIGHT" },
    { code: "26H0", description: "26H0 - INSULATED CONTAINER" },
    { code: "26T9", description: "26T9 - TANK CONTAINER" },
    { code: "28G0", description: "28G0 - HALF HIGH" },
    { code: "28T0", description: "28T0 - HALF HIGH TANK" },
    { code: "28T8", description: "28T8 - TANK FOR GAS" },
    { code: "28U1", description: "28U1 - OPEN TOP (HALF HEIGHT)" },
    { code: "28V0", description: "28V0 - VE-HALF-HEIGHT =1448 MM HEIGHT" },
    { code: "29P0", description: "29P0 - PLATFORM" },
    { code: "2EG0", description: "2EG0 - HIGH CUBE CONT. (WIDTH 2.5M)" },
    { code: "2LXX", description: "2LXX - WIDE BODY TANK" },
    { code: "30B1", description: "30B1 - BULK CONTAINER" },
    { code: "30G0", description: "30G0 - GENERAL PURPOSE CONT." },
    { code: "32R3", description: "32R3 - POWER PACK" },
    { code: "32T1", description: "32T1 - TANK CONTAINER" },
    { code: "32T6", description: "32T6 - TANK CONTAINER" },
    { code: "3LXX", description: "3LXX - WIDE BODY TANK" },
    { code: "3MB0", description: "3MB0 - HIGH BULK CONTAINER" },
    { code: "40I0", description: "40I0 - Insulated Container" },
    { code: "40V0", description: "40V0 - Ventilated Container" },
    { code: "42G0", description: "42G0 - GENERAL PURPOSE CONT." },
    { code: "42G1", description: "42G1 - GENERAL PURPOSE CONT." },
    { code: "42H0", description: "42H0 - INSULATED CONTAINER" },
    { code: "42OS", description: "42OS - OPEN SIDE" },
    { code: "42P1", description: "42P1 - FLAT (FIXED ENDS)" },
    { code: "42P3", description: "42P3 - FLAT (COLLAPSIBLE)" },
    { code: "42P4", description: "42P4 - FLAT (COLLAPSIBLE)" },
    { code: "42P6", description: "42P6 - FLAT SPACE SAVER" },
    { code: "42P8", description: "42P8 - FLAT (COLL.FLUSH FOLDING)" },
    { code: "42P9", description: "42P9 - FLAT (COLLAPSIBLE)" },
    { code: "42R1", description: "42R1 - REEFER CONTAINER" },
    { code: "42R3", description: "42R3 - REEFER CONT.(DIESEL GEN.)" },
    { code: "42R9", description: "42R9 - REEFER CONT.(NO FOOD)" },
    { code: "42S1", description: "42S1 - NAMED CARGO CONTAINER" },
    { code: "42T2", description: "42T2 - TANK CONTAINER" },
    { code: "42T5", description: "42T5 - TANK CONTAINER" },
    { code: "42T6", description: "42T6 - TANK CONTAINER" },
    { code: "42T8", description: "42T8 - TANK CONTAINER" },
    { code: "42U1", description: "42U1 - OPEN TOP CONTAINER" },
    { code: "42U6", description: "42U6 - HARDTOP CONTAINER" },
    { code: "43T5", description: "43T5 - TANK CONTAINER" },
    { code: "44ZZ", description: "44ZZ - UNSPECIFIED" },
    { code: "45B3", description: "45B3 - BULK CONTAINER" },
    { code: "45G0", description: "45G0 - HIGH CUBE CONTAINER" },
    { code: "45G1", description: "45G1 - HIGH CUBE CONT." },
    { code: "45P0", description: "45P0 - HIGH CUBE PLATFORM" },
    { code: "45P1", description: "45P1 - FLAT (COLLAPSIBLE)" },
    { code: "45P3", description: "45P3 - FLAT (COLLAPSIBLE)" },
    { code: "45P8", description: "45P8 - FLAT (COLL.FLUSH FOLDING)" },
    { code: "45R1", description: "45R1 - REEFER HIGHCUBE CONTAINER" },
    { code: "45R9", description: "45R9 - REEFER CONT.(NO FOOD)" },
    { code: "45U1", description: "45U1 - OPEN TOP CONTAINER" },
    { code: "45U6", description: "45U6 - HIGH CUBE HARDTOP CONT." },
    { code: "46H0", description: "46H0 - INSULATED CONTAINER" },
    { code: "47T9", description: "47T9 - TANK CONTAINER" },
    { code: "48G0", description: "48G0 - HALF HIGH" },
    { code: "48T8", description: "48T8 - TANK FOR GAS" },
    { code: "49P0", description: "49P0 - PLATFORM" },
    { code: "49P3", description: "49P3 - PLATFORM FLAT RACK" },
    { code: "4CG0", description: "4CG0 - GP CONTAINER (WIDTH 2.5 M)" },
    { code: "4EG1", description: "4EG1 - HIGH CUBE CONT. (WIDTH 2.5M)" },
    { code: "4MNL", description: "4MNL - SILO 40 FT" },
    { code: "72T0", description: "72T0 - TANK CONTAINER" },
    { code: "72T8", description: "72T8 - TANK CONTAINER" },
    { code: "74T0", description: "74T0 - TANK CONTAINER" },
    { code: "74T1", description: "74T1 - TANK CONTAINER" },
    { code: "74T6", description: "74T6 - TANK CONTAINER" },
    { code: "74T7", description: "74T7 - TANK CONTAINER" },
    { code: "74T8", description: "74T8 - TANK CONTAINER" },
    { code: "74ZZ", description: "74ZZ - UNSPECIFIED" },
    { code: "75T8", description: "75T8 - TANK CONTAINER" },
    { code: "A2T1", description: "A2T1 - TANK CONTAINER" },
    { code: "A2T3", description: "A2T3 - TANK CONTAINER" },
    { code: "CMT1", description: "CMT1 - TANK CONTAINER" },
    { code: "L0G0", description: "L0G0 - GENERAL PURPOSE CONT." },
    { code: "L0G1", description: "L0G1 - HIGH CUBE CONT." },
    { code: "L2G1", description: "L2G1 - HIGH CUBE CONT." },
    { code: "L2W0", description: "L2W0 - PALLETWIDE" },
    { code: "L4ZZ", description: "L4ZZ - UNSPECIFIED" },
    { code: "L5G1", description: "L5G1 - HIGH CUBE CONT." },
    { code: "L5R0", description: "L5R0 - HIGH CUBE REEFER" },
    { code: "L5R1", description: "L5R1 - REEFER CONTAINER" },
    { code: "LEG1", description: "LEG1 - HIGH CUBE CONT." },
    { code: "M0G0", description: "M0G0 - GENERAL PURPOSE CONT." },
    { code: "P0G0", description: "P0G0 - GENERAL PURPOSE CONT." },
    { code: "P5G0", description: "P5G0 - HIGH CUBE" },
    { code: "P5OS", description: "P5OS - OPEN SIDE" },
    { code: "P5R1", description: "P5R1 - REEFER CONTAINER" },
    { code: "ZZNC", description: "ZZNC - NOT CONTAINERIZED" }
  ],

  // Container Type - se guarda el code (primeras dos letras)
  containerType: [
    { code: "BB", description: "Unspecified BB" },
    { code: "BH", description: "Swap Body High" },
    { code: "BV", description: "Bulk van" },
    { code: "DV", description: "Dry van" },
    { code: "FL", description: "Flat rack" },
    { code: "FT", description: "Unspecified FT" },
    { code: "HC", description: "High cube" },
    { code: "HH", description: "Half height" },
    { code: "HO", description: "High cube open top" },
    { code: "HP", description: "High Cube Palletwide" },
    { code: "HR", description: "High cube reefer" },
    { code: "HT", description: "Hard top" },
    { code: "IS", description: "Insulated" },
    { code: "OS", description: "Open side" },
    { code: "OT", description: "Open top" },
    { code: "PL", description: "Platform flat" },
    { code: "PP", description: "Power Pack" },
    { code: "PW", description: "Palette Wide" },
    { code: "RE", description: "Reefer" },
    { code: "SH", description: "Semi Trailer High" },
    { code: "SR", description: "Low Bed Semi Trailer" },
    { code: "ST", description: "SemiTrailer" },
    { code: "SW", description: "Swap Body" },
    { code: "TH", description: "Therm Refr." },
    { code: "TK", description: "Tank" },
    { code: "TS", description: "Tank Semi Trailer" },
    { code: "VE", description: "Ventilated" },
    { code: "XX", description: "Unspecified" },
    { code: "ZZ", description: "Unspecified" }
  ],

  // Container Size - se guarda el primer número
  containerSize: [
    { value: "0", label: "0" },
    { value: "10", label: "10" },
    { value: "20", label: "20" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
    { value: "24", label: "24" },
    { value: "25", label: "25" },
    { value: "26", label: "26" },
    { value: "30", label: "30" },
    { value: "40", label: "40" },
    { value: "45", label: "45" },
    { value: "48", label: "48" },
    { value: "53", label: "53" },
    { value: "8", label: "8" }
  ],

  // Full Empty Status
  fullEmpty: [
    { value: "FULL", label: "Full" },
    { value: "EMPTY", label: "Empty" }
  ],

  // Subcontracting - se guarda Y o N en el XML
  subcontracting: [
    { value: "Y", label: "Yes", xmlValue: "Y" },
    { value: "N", label: "No", xmlValue: "N" }
  ],

  // Bundle - se guarda el número del principio
  bundle: [
    { value: "0000", label: "0000 - None" },
    { value: "100", label: "100 - Multimodal transport" },
    { value: "115", label: "115 - Multim. Rail/Truck" },
    { value: "200", label: "200 - Multi-activ.Inland" },
    { value: "300", label: "300 - Multi-activ.Log.Serv" },
    { value: "500", label: "500 - Mix activities" }
  ],

  // Commodity - se guarda el número del principio
  commodity: [
    { value: "1", label: "1 - LIVE ANIMALS" },
    { value: "2", label: "2 - MEAT AND EDIBLE MEAT" },
    { value: "3", label: "3 - FISH AND CRUSTACEANS" },
    { value: "4", label: "4 - DAIRY PRODUCE; BIRDS" },
    { value: "5", label: "5 - PRODUCTS OF ANIMAL O" },
    { value: "6", label: "6 - LIVE TREES AND OTHER" },
    { value: "7", label: "7 - EDIBLE VEGETABLES AN" },
    { value: "8", label: "8 - EDIBLE FRUIT AND NUT" },
    { value: "9", label: "9 - COFFEE, TEA, MATÉ AN" },
    { value: "10", label: "10 - CEREALS" },
    { value: "11", label: "11 - PRODUCTS OF THE MILL" },
    { value: "12", label: "12 - OIL SEEDS AND OLEAGI" },
    { value: "13", label: "13 - LAC; GUMS, RESINS AN" },
    { value: "14", label: "14 - VEGETABLE PLAITING M" },
    { value: "15", label: "15 - ANIMAL OR VEGETABLE" },
    { value: "16", label: "16 - PREPARATIONS OF MEAT" },
    { value: "17", label: "17 - SUGARS AND SUGAR CON" },
    { value: "18", label: "18 - COCOA AND COCOA PREP" },
    { value: "19", label: "19 - PREPARATIONS OF CERE" },
    { value: "20", label: "20 - PREPARATIONS OF VEGE" },
    { value: "21", label: "21 - MISCELLANEOUS EDIBLE" },
    { value: "22", label: "22 - BEVERAGES, SPIRITS A" },
    { value: "23", label: "23 - RESIDUES AND WASTE F" },
    { value: "24", label: "24 - TOBACCO AND MANUFACT" },
    { value: "25", label: "25 - SALT; SULPHUR; EARTH" },
    { value: "26", label: "26 - ORES, SLAG AND ASH" },
    { value: "27", label: "27 - MINERAL FUELS, MINER" },
    { value: "28", label: "28 - INORGANIC CHEMICALS;" },
    { value: "29", label: "29 - ORGANIC CHEMICALS" },
    { value: "30", label: "30 - PHARMACEUTICAL PRODU" },
    { value: "31", label: "31 - FERTILISERS" },
    { value: "32", label: "32 - TANNING OR DYEING EX" },
    { value: "33", label: "33 - ESSENTIAL OILS AND R" },
    { value: "34", label: "34 - SOAP, ORGANIC SURFAC" },
    { value: "35", label: "35 - ALBUMINOIDAL SUBSTAN" },
    { value: "36", label: "36 - EXPLOSIVES; PYROTECH" },
    { value: "37", label: "37 - PHOTOGRAPHIC OR CINE" },
    { value: "38", label: "38 - MISCELLANEOUS CHEMIC" },
    { value: "39", label: "39 - PLASTICS AND ARTICLE" },
    { value: "40", label: "40 - RUBBER AND ARTICLES" },
    { value: "41", label: "41 - RAW HIDES AND SKINS" },
    { value: "42", label: "42 - ARTICLES OF LEATHER;" },
    { value: "43", label: "43 - FURSKINS AND ARTIFIC" },
    { value: "44", label: "44 - WOOD AND ARTICLES OF" },
    { value: "45", label: "45 - CORK AND ARTICLES OF" },
    { value: "46", label: "46 - MANUFACTURES OF STRA" },
    { value: "47", label: "47 - PULP OF WOOD OR OF O" },
    { value: "48", label: "48 - PAPER AND PAPERBOARD" },
    { value: "49", label: "49 - PRINTED BOOKS, NEWSP" },
    { value: "50", label: "50 - SILK" },
    { value: "51", label: "51 - WOOL, FINE OR COARSE" },
    { value: "52", label: "52 - COTTON" },
    { value: "53", label: "53 - OTHER VEGETABLE TEXT" },
    { value: "54", label: "54 - MAN-MADE FILAMENTS;" },
    { value: "55", label: "55 - MAN-MADE STAPLE FIBR" },
    { value: "56", label: "56 - WADDING, FELT AND NO" },
    { value: "57", label: "57 - CARPETS AND OTHER TE" },
    { value: "58", label: "58 - SPECIAL WOVEN FABRIC" },
    { value: "59", label: "59 - IMPREGNATED, COATED," },
    { value: "60", label: "60 - KNITTED OR CROCHETED" },
    { value: "61", label: "61 - ARTICLES OF APPAREL" },
    { value: "62", label: "62 - ARTICLES OF APPAREL" },
    { value: "63", label: "63 - OTHER MADE-UP TEXTIL" },
    { value: "64", label: "64 - FOOTWEAR, GAITERS AN" },
    { value: "65", label: "65 - HEADGEAR AND PARTS T" },
    { value: "66", label: "66 - UMBRELLAS, SUN UMBRE" },
    { value: "67", label: "67 - PREPARED FEATHERS AN" },
    { value: "68", label: "68 - ARTICLES OF STONE, P" },
    { value: "69", label: "69 - CERAMIC PRODUCTS" },
    { value: "70", label: "70 - GLASS AND GLASSWARE" },
    { value: "71", label: "71 - NATURAL OR CULTURED" },
    { value: "72", label: "72 - IRON AND STEEL" },
    { value: "73", label: "73 - ARTICLES OF IRON OR" },
    { value: "74", label: "74 - COPPER AND ARTICLES" },
    { value: "75", label: "75 - NICKEL AND ARTICLES" },
    { value: "76", label: "76 - ALUMINIUM AND ARTICL" },
    { value: "78", label: "78 - LEAD AND ARTICLES TH" },
    { value: "79", label: "79 - ZINC AND ARTICLES TH" },
    { value: "80", label: "80 - TIN AND ARTICLES THE" },
    { value: "81", label: "81 - OTHER BASE METALS; C" },
    { value: "82", label: "82 - TOOLS, IMPLEMENTS, C" },
    { value: "83", label: "83 - MISCELLANEOUS ARTICL" },
    { value: "84", label: "84 - NUCLEAR REACTORS, BO" },
    { value: "85", label: "85 - ELECTRICAL MACHINERY" },
    { value: "86", label: "86 - RAILWAY OR TRAMWAY L" },
    { value: "87", label: "87 - VEHICLES OTHER THAN" },
    { value: "88", label: "88 - AIRCRAFT, SPACECRAFT" },
    { value: "89", label: "89 - SHIPS, BOATS AND FLO" },
    { value: "90", label: "90 - OPTICAL, PHOTOGRAPHI" },
    { value: "91", label: "91 - CLOCKS AND WATCHES A" },
    { value: "92", label: "92 - MUSICAL INSTRUMENTS;" },
    { value: "93", label: "93 - ARMS AND AMMUNITION;" },
    { value: "94", label: "94 - FURNITURE; BEDDING," },
    { value: "95", label: "95 - TOYS, GAMES AND SPOR" },
    { value: "96", label: "96 - MISCELLANEOUS MANUFA" },
    { value: "97", label: "97 - WORKS OF ART, COLLEC" },
    { value: "98", label: "98 - COMPLETE INDUSTRIAL" },
    { value: "99", label: "99 - SPECIAL COMBINED NOM" }
  ]
}

// Valores por defecto
export const TRUCKING_DEFAULTS = {
  activityCode: "TRK",
  pillar: "TRSP",
  buCountry: "PAN",
  serviceCountry: "PAN",
  clientType: "MEDLOG",
  incomeRebateCode: "I",
  commodity: "VER",
  ctrCategory: "STANDARD",
  repairTyp: "N/A" as string
} 