export const excelTypes = [
  {
    id: "tracking",
    name: "Tracking",
    description: "Datos de seguimiento de contenedores y logística",
    fields: [
      "FECHA",
      "CLIENTES",
      "DESDE",
      "SUB-CLIENTES",
      "HACIA",
      "B/L",
      "BUQUE",
      "TAMAÑO",
      "N° CONTENEDOR",
      "PTG ORDER",
      "STATUS",
      "VOYAGE",
      "TARIFA",
      "GASTOS PUERTO",
      "OTROS GASTOS",
      "JIRA",
      "FECHA FACTURACION",
      "DRIVER",
      "PLATE",
      "BONO",
      "RT CONTAINER",
    ],
  },
  {
    id: "invoices",
    name: "Invoices",
    description: "Datos de facturas y pagos",
    fields: [
      "Customer Name",
      "Invoice No",
      "Invoice Type",
      "Vessel",
      "Date",
      "Project Code",
      "From",
      "To",
      "Payment Term",
      "Reference No",
      "Shipping Term",
      "Delivery Address",
      "PO No",
      "Note",
      "Currency",
      "Discount",
      "Total Invoice",
      "Total",
      "Paid",
      "UnPaid",
    ],
  },
  {
    id: "transport",
    name: "Transport Services",
    description: "Servicios de transporte y traslados",
    fields: [
      "PO#",
      "DATE",
      "PICK UP TIME",
      "PICK UP",
      "DROP OFF",
      "VESSEL",
      "VOY",
      "TAULIA",
      "RANK",
      "NAME",
      "NATIONALITY",
      "TIME",
      "FLIGHT",
      "STATUS",
      "STATUS2",
      "INVOICE",
      "MONTO",
    ],
  },
]

export const mockExcelFiles = [
  {
    id: "1",
    filename: "tracking_data_mayo.xlsx",
    uploadDate: "18/05/2025",
    status: "formateado",
    type: "tracking",
    records: 13,
    mainClient: "ALMEIDA KANT",
    size: 245,
  },
  {
    id: "2",
    filename: "invoices_damico_mayo.xlsx",
    uploadDate: "17/05/2025",
    status: "formateado",
    type: "invoices",
    records: 18,
    mainClient: "D'AMICO SHIP MANAGEMENT",
    size: 189,
  },
  {
    id: "3",
    filename: "transport_services_julio.xlsx",
    uploadDate: "16/05/2025",
    status: "procesado",
    type: "transport",
    records: 22,
    mainClient: "MSC LOGISTICS",
    size: 156,
  },
]

export const mockTrackingData = [
  {
    fecha: "9/17/2022",
    clientes: "ALMEIDA KANT",
    desde: "MITSEB",
    subClientes: "",
    hacia: "BLB",
    bl: "7336875A",
    buque: "X-PRESS SHANNON",
    tamaño: "40",
    contenedor: "CTWU1601508",
    ptgOrder: "1288097",
    status: "RT",
    voyage: "32761",
    tarifa: 16.0,
    gastosPuerto: "SEA #505",
    otrosGastos: "",
    jira: "",
    fechaFacturacion: "10/26/2023",
    driver: "Matos Luis",
    plate: "",
    bono: "",
    rtContainer: "MSCU7326823",
  },
  {
    fecha: "9/17/2022",
    clientes: "ALMEIDA KANT",
    desde: "PSA",
    subClientes: "MSC",
    hacia: "CTB",
    bl: "MEDUL6827090",
    buque: "MAERSK SHIVLING",
    tamaño: "40",
    contenedor: "MSCU7326823",
    ptgOrder: "782408",
    status: "RT",
    voyage: "16308",
    tarifa: 22.0,
    gastosPuerto: "MSC #505",
    otrosGastos: "",
    jira: "",
    fechaFacturacion: "10/26/2023",
    driver: "Matos Luis",
    plate: "",
    bono: "",
    rtContainer: "CTWU1601508",
  },
]

export const mockInvoicesData = [
  {
    customerName: "D'AMICO SHIP MANAGEMENT S.R.L",
    invoiceNo: "SC-00604",
    invoiceType: "Invoice",
    vessel: "HIGH ADVENTURE",
    date: "07-05-2025",
    projectCode: "PTYSS25-000010",
    from: "",
    to: "T30",
    paymentTerm: "",
    referenceNo: "HADXENG 5063330",
    shippingTerm: "",
    deliveryAddress: "HOMEPORT",
    poNo: "",
    note: "",
    currency: "USD",
    discount: "10",
    totalInvoice: "xxxxxxxxxxxx",
    total: "xxxxxxxxxxxx",
    paid: "xxxxxxxxxxxx",
    unpaid: "xxxxxxxxxxxx",
  },
  {
    customerName: "WSM Global Services Limited",
    invoiceNo: "SC-00599",
    invoiceType: "Invoice",
    vessel: "AS SAVANNA",
    date: "02-05-2025",
    projectCode: "PTYSS25-000047",
    from: "",
    to: "T30",
    paymentTerm: "",
    referenceNo: "MPSA 25-0125-1",
    shippingTerm: "",
    deliveryAddress: "MPSA 25-0125-1",
    poNo: "",
    note: "",
    currency: "USD",
    discount: "",
    totalInvoice: "xxxxxxxxxxxx",
    total: "xxxxxxxxxxxx",
    paid: "xxxxxxxxxxxx",
    unpaid: "xxxxxxxxxxxx",
  },
]

export const mockTransportData = [
  {
    po: "BP#001",
    date: "1-Jul-24",
    pickUpTime: "9:00",
    pickUp: "MARRIOTT AC",
    dropOff: "PSA PORT",
    vessel: "MSC LUDOVICA",
    voy: "FR423W",
    taulia: "ECR000669",
    rank: "THIRD ENGINEER",
    name: "ALMEIDA ALLISTER VINSON",
    nationality: "INDIA",
    time: "",
    flight: "",
    status: "",
    status2: "",
    invoice: "AG-10",
    monto: "",
  },
  {
    po: "BP#002",
    date: "1-Jul-24",
    pickUpTime: "9:00",
    pickUp: "MARRIOTT FINISTERRE",
    dropOff: "PSA PORT",
    vessel: "MSC LUDOVICA",
    voy: "FR423W",
    taulia: "ECR000669",
    rank: "CHIEF OFFICER",
    name: "ARANAS JOEVEN",
    nationality: "PHILIPPINES",
    time: "",
    flight: "",
    status: "",
    status2: "",
    invoice: "AG-11",
    monto: "",
  },
]

export const mockInvoices = [
  {
    id: "1",
    invoiceNumber: "AG-1608",
    client: "ALMEIDA KANT",
    customerRuc: "155600922-2-2015",
    customerAddress: "PANAMA PACIFICO, INTERNATIONAL BUSINESS PARK",
    customerPhone: "(507) 838-9806",
    date: "18/05/2025",
    amount: "450.00",
    currency: "USD",
    status: "creada",
    xmlGenerated: true,
    type: "tracking",
  },
  {
    id: "2",
    invoiceNumber: "AG-1609",
    client: "D'AMICO SHIP MANAGEMENT S.R.L",
    customerRuc: "155600922-2-2016",
    customerAddress: "COLON FREE ZONE, BUILDING 245",
    customerPhone: "(507) 441-2345",
    date: "17/05/2025",
    amount: "320.00",
    currency: "USD",
    status: "enviada",
    xmlGenerated: true,
    type: "invoices",
  },
]
